// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timescale.Api.Infrastructure;

#nullable disable

namespace Timescale.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226210719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timescale.Api.Domain.Entities.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Timescale.Api.Domain.Entities.ResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstOperationRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TimeDelta")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Timescale.Api.Domain.Entities.ValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Timescale.Api.Domain.Entities.ResultEntity", b =>
                {
                    b.HasOne("Timescale.Api.Domain.Entities.FileEntity", "File")
                        .WithOne("Result")
                        .HasForeignKey("Timescale.Api.Domain.Entities.ResultEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Timescale.Api.Domain.Entities.ValueEntity", b =>
                {
                    b.HasOne("Timescale.Api.Domain.Entities.FileEntity", "File")
                        .WithMany("Values")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Timescale.Api.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
